### ISSUE TITLE
Logo For Utility Bills

### ISSUE THREAD

**Issue by zularizal** [TareqNewazShahriar/Distributing-Utility-Cost#1]
Hi @TareqNewazShahriar , I am a graphic designer, I want to help you in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. What do you think?

**Comment by TareqNewazShahriar** [comment]
Woow!! That sounds cool! Is it for free?

One thing - this is just an app for personal use. So... will that logo work going to help you in any way?

**Comment by zularizal** [comment]
Yes, it's free.

I hope with the logo that I design can help you complete your project ...

Please Wait, I will design a logo for this project..

**Comment by TareqNewazShahriar** [comment]
Okay. That's generous of you.

**Comment by zularizal** [comment]
How about this? Which one do you like?

![logo](https://user-images.githubusercontent.com/38547278/40581145-3cd6bab6-617b-11e8-8980-5be9ba7e5653.png)

**Comment by TareqNewazShahriar** [comment]
I will go for the first one. Could you do one thing for me - I think removing the $ sign would be better.

**Comment by zularizal** [comment]
Sure, like this?

![g4295](https://user-images.githubusercontent.com/38547278/40591532-10e92b9c-623d-11e8-85c3-dbd0e46437a0.png)

**Comment by TareqNewazShahriar** [comment]
Yep, perfect.

**Comment by zularizal** [comment]
Hi @TareqNewazShahriar  , I have uploaded the logo to the drive, you can download the logo on this link.

https://drive.google.com/open?id=1cR16nD12Xnvh55B-XLenGS7ZW9YuxMon

 And I've sent a pull request for you, please check #2

**Comment by TareqNewazShahriar** [comment]
That's a load of different formats of icons in drive.

Your commits merged. So my app got icon.

How can I say thanks to you? Let me know is there anything I can do for you.

**Comment by zularizal** [comment]
It's free, I do not want anything, I just want you to continue developing this project. 

Okay, i will close this issue

**Comment by TareqNewazShahriar** [comment]
Thank you so much

**Comment by zularizal** [comment]
Okay
